// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: especificacao.flex

import java_cup.runtime.*;


@SuppressWarnings("fallthrough")
class scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\121\u0100\1\u2600\4\u0100\1\u2700"+
    "\1\u0100\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\1\u2d00\53\u0100"+
    "\1\u2e00\10\u2f00\31\u1f00\1\u0100\1\u3000\1\u3100\1\u0100\1\u3200"+
    "\1\u3300\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900\1\u3a00"+
    "\1\u0100\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000\1\u4100"+
    "\1\u4200\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800\1\u4900"+
    "\1\u4a00\1\u4b00\1\u4c00\1\u4d00\1\u4e00\1\u1f00\1\u4f00\1\u5000"+
    "\1\u5100\1\u5200\3\u0100\1\u5300\1\u5400\1\u5500\12\u1f00\4\u0100"+
    "\1\u5600\17\u1f00\2\u0100\1\u5700\41\u1f00\2\u0100\1\u5800\1\u5900"+
    "\2\u1f00\1\u5a00\1\u5b00\27\u0100\1\u5c00\4\u0100\1\u5d00\1\u5e00"+
    "\42\u1f00\1\u0100\1\u5f00\1\u6000\11\u1f00\1\u6100\24\u1f00\1\u6200"+
    "\1\u6300\1\u1f00\1\u6400\1\u6500\1\u6600\1\u6700\2\u1f00\1\u6800"+
    "\5\u1f00\1\u6900\1\u6a00\1\u6b00\5\u1f00\1\u6c00\1\u6d00\2\u1f00"+
    "\1\u6e00\1\u1f00\1\u6f00\14\u1f00\1\u7000\4\u1f00\246\u0100\1\u7100"+
    "\20\u0100\1\u7200\1\u7300\25\u0100\1\u7400\34\u0100\1\u7500\14\u1f00"+
    "\2\u0100\1\u7600\5\u1f00\23\u0100\1\u7700\u0aec\u1f00\1\u7800\1\u7900"+
    "\u02fe\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\4\16\0\5\1\1\5"+
    "\1\6\1\1\1\7\1\1\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\11\23"+
    "\1\1\1\24\1\25\1\26\1\27\2\1\32\7\1\30"+
    "\1\31\1\32\1\33\1\7\1\1\1\34\1\35\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\2\7\1\45"+
    "\1\7\1\46\1\47\1\50\1\7\1\51\1\52\1\53"+
    "\1\54\1\7\1\55\3\7\1\56\1\57\1\60\1\1"+
    "\6\0\1\61\32\0\2\1\4\7\4\1\1\7\2\1"+
    "\1\0\7\1\1\7\4\1\1\7\5\1\27\7\1\1"+
    "\37\7\1\1\u01ca\7\4\1\14\7\16\1\5\7\7\1"+
    "\1\7\1\1\1\7\21\1\160\0\5\7\1\1\2\7"+
    "\2\1\4\7\1\1\1\7\6\1\1\7\1\1\3\7"+
    "\1\1\1\7\1\1\24\7\1\1\123\7\1\1\213\7"+
    "\1\1\5\0\2\1\246\7\1\1\46\7\2\1\1\7"+
    "\6\1\51\7\6\1\1\7\1\1\55\0\1\1\1\0"+
    "\1\1\2\0\1\1\2\0\1\1\1\0\10\1\33\7"+
    "\4\1\4\7\15\1\6\0\5\1\1\7\4\1\13\0"+
    "\1\1\1\0\3\1\53\7\25\0\12\62\4\1\2\7"+
    "\1\0\143\7\1\1\1\7\10\0\1\1\6\0\2\7"+
    "\2\0\1\1\4\0\2\7\12\62\3\7\2\1\1\7"+
    "\17\1\1\0\1\7\1\0\36\7\33\0\2\1\131\7"+
    "\13\0\1\7\16\1\12\62\41\7\11\0\2\7\4\1"+
    "\1\7\2\1\1\0\30\7\4\0\1\7\11\0\1\7"+
    "\3\0\1\7\5\0\22\1\31\7\3\0\4\1\13\7"+
    "\65\1\25\7\1\1\22\7\13\1\61\0\66\7\3\0"+
    "\1\7\22\0\1\7\7\0\12\7\2\0\2\1\12\62"+
    "\1\1\20\7\3\0\1\1\10\7\2\1\2\7\2\1"+
    "\26\7\1\1\7\7\1\1\1\7\3\1\4\7\2\1"+
    "\1\0\1\7\7\0\2\1\2\0\2\1\3\0\1\7"+
    "\10\1\1\0\4\1\2\7\1\1\3\7\2\0\2\1"+
    "\12\62\4\7\7\1\2\7\1\1\1\0\2\1\3\0"+
    "\1\1\6\7\4\1\2\7\2\1\26\7\1\1\7\7"+
    "\1\1\2\7\1\1\2\7\1\1\2\7\2\1\1\0"+
    "\1\1\5\0\4\1\2\0\2\1\3\0\3\1\1\0"+
    "\7\1\4\7\1\1\1\7\7\1\12\62\2\0\3\7"+
    "\1\0\13\1\3\0\1\1\11\7\1\1\3\7\1\1"+
    "\26\7\1\1\7\7\1\1\2\7\1\1\5\7\2\1"+
    "\1\0\1\7\10\0\1\1\3\0\1\1\3\0\2\1"+
    "\1\7\17\1\2\7\2\0\2\1\12\62\1\1\1\7"+
    "\7\1\1\7\6\0\1\1\3\0\1\1\10\7\2\1"+
    "\2\7\2\1\26\7\1\1\7\7\1\1\2\7\1\1"+
    "\5\7\2\1\1\0\1\7\7\0\2\1\2\0\2\1"+
    "\3\0\7\1\3\0\4\1\2\7\1\1\3\7\2\0"+
    "\2\1\12\62\1\1\1\7\20\1\1\0\1\7\1\1"+
    "\6\7\3\1\3\7\1\1\4\7\3\1\2\7\1\1"+
    "\1\7\1\1\2\7\3\1\2\7\3\1\3\7\3\1"+
    "\14\7\4\1\5\0\3\1\3\0\1\1\4\0\2\1"+
    "\1\7\6\1\1\0\16\1\12\62\11\1\1\7\6\1"+
    "\5\0\10\7\1\1\3\7\1\1\27\7\1\1\20\7"+
    "\3\1\1\7\7\0\1\1\3\0\1\1\4\0\7\1"+
    "\2\0\1\1\3\7\5\1\2\7\2\0\2\1\12\62"+
    "\20\1\1\7\3\0\1\1\10\7\1\1\3\7\1\1"+
    "\27\7\1\1\12\7\1\1\5\7\2\1\1\0\1\7"+
    "\7\0\1\1\3\0\1\1\4\0\7\1\2\0\7\1"+
    "\1\7\1\1\2\7\2\0\2\1\12\62\1\1\2\7"+
    "\15\1\4\0\11\7\1\1\3\7\1\1\51\7\2\0"+
    "\1\7\7\0\1\1\3\0\1\1\4\0\1\7\5\1"+
    "\3\7\1\0\7\1\3\7\2\0\2\1\12\62\12\1"+
    "\6\7\1\1\3\0\1\1\22\7\3\1\30\7\1\1"+
    "\11\7\1\1\1\7\2\1\7\7\3\1\1\0\4\1"+
    "\6\0\1\1\1\0\1\1\10\0\6\1\12\62\2\1"+
    "\2\0\15\1\60\7\1\0\2\7\7\0\4\1\10\7"+
    "\10\0\1\1\12\62\47\1\2\7\1\1\1\7\1\1"+
    "\5\7\1\1\30\7\1\1\1\7\1\1\12\7\1\0"+
    "\2\7\11\0\1\7\2\1\5\7\1\1\1\7\1\1"+
    "\6\0\2\1\12\62\2\1\4\7\40\1\1\7\27\1"+
    "\2\0\6\1\12\62\13\1\1\0\1\1\1\0\1\1"+
    "\1\0\4\1\2\0\10\7\1\1\44\7\4\1\24\0"+
    "\1\1\2\0\5\7\13\0\1\1\44\0\11\1\1\0"+
    "\71\1\53\7\24\0\1\7\12\62\6\1\6\7\4\0"+
    "\4\7\3\0\1\7\3\0\2\7\7\0\3\7\4\0"+
    "\15\7\14\0\1\7\1\0\12\62\4\0\2\1\46\7"+
    "\1\1\1\7\5\1\1\7\2\1\53\7\1\1\115\7"+
    "\1\1\4\7\2\1\7\7\1\1\1\7\1\1\4\7"+
    "\2\1\51\7\1\1\4\7\2\1\41\7\1\1\4\7"+
    "\2\1\7\7\1\1\1\7\1\1\4\7\2\1\17\7"+
    "\1\1\71\7\1\1\4\7\2\1\103\7\2\1\3\0"+
    "\40\1\20\7\20\1\126\7\2\1\6\7\3\1\u016c\7"+
    "\2\1\21\7\1\1\32\7\5\1\113\7\3\1\13\7"+
    "\7\1\15\7\1\1\4\7\3\0\13\1\22\7\3\0"+
    "\13\1\22\7\2\0\14\1\15\7\1\1\3\7\1\1"+
    "\2\0\14\1\64\7\40\0\3\1\1\7\3\1\2\7"+
    "\1\0\2\1\12\62\41\1\4\0\1\1\12\62\6\1"+
    "\131\7\7\1\5\7\2\0\42\7\1\0\1\7\5\1"+
    "\106\7\12\1\37\7\1\1\14\0\4\1\14\0\12\1"+
    "\12\62\36\7\2\1\5\7\13\1\54\7\4\1\32\7"+
    "\6\1\12\62\46\1\27\7\5\0\4\1\65\7\12\0"+
    "\1\1\35\0\2\1\1\0\12\62\6\1\12\62\15\1"+
    "\1\7\10\1\16\0\1\1\2\0\77\1\5\0\57\7"+
    "\21\0\7\7\4\1\12\62\21\1\11\0\14\1\3\0"+
    "\36\7\15\0\2\7\12\62\54\7\16\0\14\1\44\7"+
    "\24\0\10\1\12\62\3\1\3\7\12\62\44\7\2\1"+
    "\11\7\7\1\53\7\2\1\3\7\20\1\3\0\1\1"+
    "\25\0\4\7\1\0\6\7\1\0\2\7\3\0\1\7"+
    "\5\1\300\7\72\0\1\1\5\0\26\7\2\1\6\7"+
    "\2\1\46\7\2\1\6\7\2\1\10\7\1\1\1\7"+
    "\1\1\1\7\1\1\1\7\1\1\37\7\2\1\65\7"+
    "\1\1\7\7\1\1\1\7\3\1\3\7\1\1\7\7"+
    "\3\1\4\7\2\1\6\7\4\1\15\7\5\1\3\7"+
    "\1\1\7\7\16\1\5\0\30\1\2\3\5\0\20\1"+
    "\2\7\23\1\1\7\13\1\5\0\1\1\12\0\1\1"+
    "\1\7\15\1\1\7\20\1\15\7\3\1\40\7\20\1"+
    "\15\0\4\1\1\0\3\1\14\0\21\1\1\7\4\1"+
    "\1\7\2\1\12\7\1\1\1\7\3\1\5\7\6\1"+
    "\1\7\1\1\1\7\1\1\1\7\1\1\4\7\1\1"+
    "\13\7\2\1\4\7\5\1\5\7\4\1\1\7\21\1"+
    "\51\7\u0177\1\57\7\1\1\57\7\1\1\205\7\6\1"+
    "\4\7\3\0\2\7\14\1\46\7\1\1\1\7\5\1"+
    "\1\7\2\1\70\7\7\1\1\7\17\1\1\0\27\7"+
    "\11\1\7\7\1\1\7\7\1\1\7\7\1\1\7\7"+
    "\1\1\7\7\1\1\7\7\1\1\7\7\1\1\7\7"+
    "\1\1\40\0\57\1\1\7\325\1\3\7\31\1\11\7"+
    "\6\0\1\1\5\7\2\1\5\7\4\1\126\7\2\1"+
    "\2\0\2\1\3\7\1\1\132\7\1\1\4\7\5\1"+
    "\53\7\1\1\136\7\21\1\40\7\60\1\320\7\100\1"+
    "\375\7\3\1\215\7\103\1\56\7\2\1\15\7\3\1"+
    "\20\7\12\62\2\7\24\1\57\7\1\0\4\1\12\0"+
    "\1\1\37\7\2\0\120\7\2\0\45\1\11\7\2\1"+
    "\147\7\2\1\65\7\2\1\11\7\52\1\15\7\1\0"+
    "\3\7\1\0\4\7\1\0\27\7\5\0\4\1\1\0"+
    "\13\1\1\7\7\1\64\7\14\1\2\0\62\7\22\0"+
    "\12\1\12\62\6\1\22\0\6\7\3\1\1\7\1\1"+
    "\2\7\1\0\12\62\34\7\10\0\2\1\27\7\15\0"+
    "\14\1\35\7\3\1\4\0\57\7\16\0\16\1\1\7"+
    "\12\62\6\1\5\7\1\0\12\7\12\62\5\7\1\1"+
    "\51\7\16\0\11\1\3\7\1\0\10\7\2\0\2\1"+
    "\12\62\6\1\27\7\3\1\1\7\3\0\62\7\1\0"+
    "\1\7\3\0\2\7\2\0\5\7\2\0\1\7\1\0"+
    "\1\7\30\1\3\7\2\1\13\7\5\0\2\1\3\7"+
    "\2\0\12\1\6\7\2\1\6\7\2\1\6\7\11\1"+
    "\7\7\1\1\7\7\1\1\53\7\1\1\16\7\6\1"+
    "\163\7\10\0\1\1\2\0\2\1\12\62\6\1\244\7"+
    "\14\1\27\7\4\1\61\7\4\1\u0100\3\156\7\2\1"+
    "\152\7\46\1\7\7\14\1\5\7\5\1\1\7\1\0"+
    "\12\7\1\1\15\7\1\1\5\7\1\1\1\7\1\1"+
    "\2\7\1\1\2\7\1\1\154\7\41\1\153\7\22\1"+
    "\100\7\2\1\66\7\50\1\15\7\3\1\20\0\20\1"+
    "\20\0\3\1\2\7\30\1\3\7\31\1\1\7\6\1"+
    "\5\7\1\1\207\7\2\1\1\0\4\1\1\7\13\1"+
    "\12\62\7\1\32\7\4\1\1\7\1\1\32\7\13\1"+
    "\131\7\3\1\6\7\2\1\6\7\2\1\6\7\2\1"+
    "\3\7\3\1\2\7\3\1\2\7\22\1\3\0\4\1"+
    "\14\7\1\1\32\7\1\1\23\7\1\1\2\7\1\1"+
    "\17\7\2\1\16\7\42\1\173\7\105\1\65\7\210\1"+
    "\1\0\202\1\35\7\3\1\61\7\17\1\1\0\37\1"+
    "\40\7\15\1\36\7\5\1\46\7\5\0\5\1\36\7"+
    "\2\1\44\7\4\1\10\7\1\1\5\7\52\1\236\7"+
    "\2\1\12\62\6\1\44\7\4\1\44\7\4\1\50\7"+
    "\10\1\64\7\234\1\67\7\11\1\26\7\12\1\10\7"+
    "\230\1\6\7\2\1\1\7\1\1\54\7\1\1\2\7"+
    "\3\1\1\7\2\1\27\7\12\1\27\7\11\1\37\7"+
    "\101\1\23\7\1\1\2\7\12\1\26\7\12\1\32\7"+
    "\106\1\70\7\6\1\2\7\100\1\1\7\3\0\1\1"+
    "\2\0\5\1\4\0\4\7\1\1\3\7\1\1\35\7"+
    "\2\1\3\0\4\1\1\0\40\1\35\7\3\1\35\7"+
    "\43\1\10\7\1\1\34\7\2\0\31\1\66\7\12\1"+
    "\26\7\12\1\23\7\15\1\22\7\156\1\111\7\67\1"+
    "\63\7\15\1\63\7\15\1\44\7\4\0\10\1\12\62"+
    "\u0146\1\52\7\1\1\2\0\3\1\2\7\116\1\35\7"+
    "\12\1\1\7\10\1\26\7\13\0\137\1\25\7\33\1"+
    "\27\7\11\1\3\0\65\7\17\0\37\1\12\62\17\1"+
    "\4\0\55\7\13\0\2\1\1\0\17\1\1\0\2\1"+
    "\31\7\7\1\12\62\6\1\3\0\44\7\16\0\1\1"+
    "\12\62\4\1\1\7\2\0\1\7\10\1\43\7\1\0"+
    "\2\1\1\7\11\1\3\0\60\7\16\0\4\7\4\1"+
    "\4\0\1\1\2\0\12\62\1\7\1\1\1\7\43\1"+
    "\22\7\1\1\31\7\14\0\6\1\1\0\101\1\7\7"+
    "\1\1\1\7\1\1\4\7\1\1\17\7\1\1\12\7"+
    "\7\1\57\7\14\0\5\1\12\62\6\1\4\0\1\1"+
    "\10\7\2\1\2\7\2\1\26\7\1\1\7\7\1\1"+
    "\2\7\1\1\5\7\1\1\2\0\1\7\7\0\2\1"+
    "\2\0\2\1\3\0\2\1\1\7\6\1\1\0\5\1"+
    "\5\7\2\0\2\1\7\0\3\1\5\0\213\1\65\7"+
    "\22\0\4\7\5\1\12\62\4\1\1\0\3\7\36\1"+
    "\60\7\24\0\2\7\1\1\1\7\10\1\12\62\246\1"+
    "\57\7\7\0\2\1\11\0\27\1\4\7\2\0\42\1"+
    "\60\7\21\0\3\1\1\7\13\1\12\62\46\1\53\7"+
    "\15\0\1\7\7\1\12\62\66\1\33\7\2\1\17\0"+
    "\4\1\12\62\306\1\54\7\17\0\145\1\100\7\12\62"+
    "\25\1\10\7\2\1\1\7\2\1\10\7\1\1\2\7"+
    "\1\1\30\7\6\0\1\1\2\0\2\1\4\0\1\7"+
    "\1\0\1\7\2\0\14\1\12\0\106\1\10\7\2\1"+
    "\47\7\7\0\2\1\7\0\1\7\1\1\1\7\1\0"+
    "\33\1\1\7\12\0\50\7\7\0\1\7\4\0\10\1"+
    "\1\0\10\1\1\7\13\0\56\7\20\0\3\1\1\7"+
    "\42\1\71\7\7\1\11\7\1\1\45\7\10\0\1\1"+
    "\10\0\1\7\17\1\12\62\30\1\36\7\2\1\26\0"+
    "\1\1\16\0\111\1\7\7\1\1\2\7\1\1\46\7"+
    "\6\0\3\1\1\0\1\1\2\0\1\1\7\0\1\7"+
    "\1\0\10\1\12\62\6\1\6\7\1\1\2\7\1\1"+
    "\40\7\5\0\1\1\2\0\1\1\5\0\1\7\7\1"+
    "\12\62\u0136\1\23\7\4\0\271\1\1\7\54\1\4\7"+
    "\37\1\232\7\146\1\157\7\21\1\304\7\274\1\57\7"+
    "\1\1\11\0\307\1\107\7\271\1\71\7\7\1\37\7"+
    "\1\1\12\62\146\1\36\7\2\1\5\0\13\1\60\7"+
    "\7\0\11\1\4\7\14\1\12\62\11\1\25\7\5\1"+
    "\23\7\260\1\100\7\200\1\113\7\4\1\1\0\1\7"+
    "\67\0\7\1\4\0\15\7\100\1\2\7\1\1\1\7"+
    "\1\0\13\1\2\0\16\1\370\7\10\1\326\7\52\1"+
    "\11\7\367\1\37\7\61\1\3\7\21\1\4\7\10\1"+
    "\u018c\7\4\1\153\7\5\1\15\7\3\1\11\7\7\1"+
    "\12\7\3\1\2\0\1\1\4\0\301\1\5\0\3\1"+
    "\26\0\2\1\7\0\36\1\4\0\224\1\3\0\273\1"+
    "\125\7\1\1\107\7\1\1\2\7\2\1\1\7\2\1"+
    "\2\7\2\1\4\7\1\1\14\7\1\1\1\7\1\1"+
    "\7\7\1\1\101\7\1\1\4\7\2\1\10\7\1\1"+
    "\7\7\1\1\34\7\1\1\4\7\1\1\5\7\1\1"+
    "\1\7\3\1\7\7\1\1\u0154\7\2\1\31\7\1\1"+
    "\31\7\1\1\37\7\1\1\31\7\1\1\37\7\1\1"+
    "\31\7\1\1\37\7\1\1\31\7\1\1\37\7\1\1"+
    "\31\7\1\1\10\7\2\1\62\62\67\0\4\1\62\0"+
    "\10\1\1\0\16\1\1\0\26\1\5\0\1\1\17\0"+
    "\120\1\7\0\1\1\21\0\2\1\7\0\1\1\2\0"+
    "\1\1\5\0\325\1\55\7\3\1\7\0\7\7\2\1"+
    "\12\62\4\1\1\7\u0171\1\54\7\4\0\12\62\5\1"+
    "\306\7\13\1\7\0\51\1\104\7\7\0\1\7\4\1"+
    "\12\62\u0156\1\1\7\117\1\4\7\1\1\33\7\1\1"+
    "\2\7\1\1\1\7\2\1\1\7\1\1\12\7\1\1"+
    "\4\7\1\1\1\7\1\1\1\7\6\1\1\7\4\1"+
    "\1\7\1\1\1\7\1\1\1\7\1\1\3\7\1\1"+
    "\2\7\1\1\1\7\2\1\1\7\1\1\1\7\1\1"+
    "\1\7\1\1\1\7\1\1\1\7\1\1\2\7\1\1"+
    "\1\7\2\1\4\7\1\1\7\7\1\1\4\7\1\1"+
    "\4\7\1\1\1\7\1\1\12\7\1\1\21\7\5\1"+
    "\3\7\1\1\5\7\1\1\21\7\u0134\1\12\0\6\1"+
    "\336\7\42\1\65\7\13\1\336\7\2\1\u0182\7\16\1"+
    "\u0131\7\37\1\36\7\342\1\113\7\266\1\1\0\36\1"+
    "\140\0\200\1\360\0\20\1";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[31232];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\1\3\1\4\1\5\1\6\2\1"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\1\1\15"+
    "\2\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\11\6\1\26\1\1\1\27\1\1\1\30\1\31\1\32"+
    "\1\33\5\0\1\34\6\6\1\35\5\6\1\36\1\37"+
    "\1\40\1\41\1\42\1\43\1\44\5\6\1\45\1\46"+
    "\4\6\1\47\1\50\1\51\3\6\1\52\1\53\2\6"+
    "\1\44\1\6\1\54\1\55\2\6\1\47\1\46";

  private static int [] zzUnpackAction() {
    int [] result = new int[98];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\146\0\146\0\146\0\146\0\231"+
    "\0\314\0\377\0\146\0\146\0\146\0\146\0\146\0\146"+
    "\0\u0132\0\146\0\u0165\0\u0198\0\146\0\146\0\u01cb\0\146"+
    "\0\146\0\146\0\146\0\u01fe\0\u0231\0\u0264\0\u0297\0\u02ca"+
    "\0\u02fd\0\u0330\0\u0363\0\u0396\0\146\0\u03c9\0\146\0\u0165"+
    "\0\u03fc\0\146\0\u042f\0\146\0\u0462\0\u0495\0\u04c8\0\u0132"+
    "\0\u0165\0\146\0\u04fb\0\u052e\0\u0561\0\u0594\0\u05c7\0\u05fa"+
    "\0\231\0\u062d\0\u0660\0\u0693\0\u06c6\0\u06f9\0\146\0\146"+
    "\0\146\0\146\0\146\0\146\0\146\0\u072c\0\u075f\0\u0792"+
    "\0\u07c5\0\u07f8\0\231\0\u082b\0\u085e\0\u0891\0\u08c4\0\u08f7"+
    "\0\u092a\0\231\0\231\0\u095d\0\u0990\0\u09c3\0\231\0\231"+
    "\0\u09f6\0\u0a29\0\231\0\u0a5c\0\231\0\231\0\u0a8f\0\u0ac2"+
    "\0\231\0\231";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[98];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\2\3\1\4\1\5\1\3\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\3\1\32\1\33\1\10\1\34\1\35\1\10\1\36"+
    "\1\37\2\10\1\40\3\10\1\41\1\10\1\42\1\43"+
    "\1\10\1\44\1\45\1\46\1\47\1\5\1\50\2\51"+
    "\1\5\1\51\1\5\1\51\1\52\22\51\1\53\31\51"+
    "\63\0\1\10\6\0\1\10\12\0\2\10\10\0\22\10"+
    "\3\0\2\10\10\0\1\54\61\0\1\55\24\0\3\55"+
    "\1\56\2\55\1\56\1\55\1\56\6\55\1\56\2\55"+
    "\27\0\2\57\36\0\1\57\20\0\1\60\1\0\2\61"+
    "\36\0\1\61\20\0\1\60\1\0\2\24\36\0\1\61"+
    "\26\0\1\62\34\0\1\10\6\0\1\10\12\0\2\10"+
    "\10\0\13\10\1\63\6\10\3\0\3\10\6\0\1\10"+
    "\12\0\2\10\10\0\7\10\1\64\12\10\3\0\3\10"+
    "\6\0\1\10\12\0\2\10\10\0\11\10\1\65\10\10"+
    "\3\0\3\10\6\0\1\10\12\0\2\10\10\0\1\66"+
    "\10\10\1\67\1\10\1\70\6\10\3\0\3\10\6\0"+
    "\1\10\12\0\2\10\10\0\5\10\1\71\4\10\1\72"+
    "\7\10\3\0\3\10\6\0\1\10\12\0\2\10\10\0"+
    "\15\10\1\73\4\10\3\0\3\10\6\0\1\10\12\0"+
    "\2\10\10\0\2\10\1\74\17\10\3\0\3\10\6\0"+
    "\1\10\12\0\2\10\10\0\15\10\1\75\4\10\3\0"+
    "\3\10\6\0\1\10\12\0\2\10\10\0\7\10\1\76"+
    "\12\10\3\0\2\10\57\0\1\77\3\0\2\51\1\0"+
    "\1\51\1\0\1\51\1\0\22\51\1\0\31\51\6\0"+
    "\1\100\37\0\1\101\2\0\1\102\1\0\1\103\20\0"+
    "\1\104\62\0\1\104\12\0\1\55\60\0\2\57\1\105"+
    "\35\0\1\57\1\10\6\0\1\10\12\0\2\10\10\0"+
    "\13\10\1\106\6\10\3\0\3\10\6\0\1\10\12\0"+
    "\2\10\10\0\1\107\21\10\3\0\3\10\6\0\1\10"+
    "\12\0\2\10\10\0\16\10\1\110\3\10\3\0\3\10"+
    "\6\0\1\10\12\0\2\10\10\0\11\10\1\111\10\10"+
    "\3\0\3\10\6\0\1\10\12\0\2\10\10\0\13\10"+
    "\1\112\6\10\3\0\3\10\6\0\1\10\12\0\2\10"+
    "\10\0\15\10\1\113\4\10\3\0\3\10\6\0\1\10"+
    "\12\0\2\10\10\0\17\10\1\114\2\10\3\0\3\10"+
    "\6\0\1\10\12\0\2\10\10\0\10\10\1\115\11\10"+
    "\3\0\3\10\6\0\1\10\12\0\2\10\10\0\1\116"+
    "\21\10\3\0\3\10\6\0\1\10\12\0\2\10\10\0"+
    "\20\10\1\117\1\10\3\0\3\10\6\0\1\10\12\0"+
    "\2\10\10\0\10\10\1\120\11\10\3\0\3\10\6\0"+
    "\1\10\12\0\2\10\10\0\11\10\1\121\10\10\3\0"+
    "\3\10\6\0\1\10\12\0\2\10\10\0\15\10\1\122"+
    "\4\10\3\0\3\10\6\0\1\10\12\0\2\10\10\0"+
    "\4\10\1\123\15\10\3\0\3\10\6\0\1\10\12\0"+
    "\2\10\10\0\16\10\1\117\3\10\3\0\3\10\6\0"+
    "\1\10\12\0\2\10\10\0\1\124\21\10\3\0\3\10"+
    "\6\0\1\10\12\0\2\10\10\0\4\10\1\125\15\10"+
    "\3\0\3\10\6\0\1\10\12\0\2\10\10\0\12\10"+
    "\1\126\7\10\3\0\3\10\6\0\1\10\12\0\2\10"+
    "\10\0\12\10\1\127\7\10\3\0\3\10\6\0\1\10"+
    "\12\0\2\10\10\0\4\10\1\130\15\10\3\0\3\10"+
    "\6\0\1\10\12\0\2\10\10\0\11\10\1\131\10\10"+
    "\3\0\3\10\6\0\1\10\12\0\2\10\10\0\4\10"+
    "\1\132\15\10\3\0\3\10\6\0\1\10\12\0\2\10"+
    "\10\0\17\10\1\133\2\10\3\0\3\10\6\0\1\10"+
    "\12\0\2\10\10\0\6\10\1\134\13\10\3\0\3\10"+
    "\6\0\1\10\12\0\2\10\10\0\17\10\1\135\2\10"+
    "\3\0\3\10\6\0\1\10\12\0\2\10\10\0\4\10"+
    "\1\136\15\10\3\0\3\10\6\0\1\10\12\0\2\10"+
    "\10\0\1\137\21\10\3\0\3\10\6\0\1\10\12\0"+
    "\2\10\10\0\4\10\1\140\15\10\3\0\3\10\6\0"+
    "\1\10\12\0\2\10\10\0\12\10\1\141\7\10\3\0"+
    "\3\10\6\0\1\10\12\0\2\10\10\0\15\10\1\142"+
    "\4\10\3\0\2\10";

  private static int [] zzUnpacktrans() {
    int [] result = new int[2805];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\5\11\3\1\6\11\1\1\1\11\2\1\2\11"+
    "\1\1\4\11\11\1\1\11\1\1\1\11\2\1\1\11"+
    "\1\1\1\11\5\0\1\11\14\1\7\11\35\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[98];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
     	StringBuffer string = new StringBuffer();
	private Symbol symbol(int type) {
		return new Symbol(type, yyline, yycolumn);
	}
	private Symbol symbol(int type, Object value) {
		return new Symbol(type, yyline, yycolumn, value);
	}


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
 System.out.println("Codigo analisado com sucesso"); 
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { 
            }
          // fall through
          case 46: break;
          case 2:
            { System.out.println("");
            }
          // fall through
          case 47: break;
          case 3:
            { throw new Error("charactere ilegal <"+yytext()+">");
            }
          // fall through
          case 48: break;
          case 4:
            { return symbol(sym.NOT);
            }
          // fall through
          case 49: break;
          case 5:
            { string.setLength(0); yybegin(STRING);
            }
          // fall through
          case 50: break;
          case 6:
            { return symbol(sym.IDENTIFIER);
            }
          // fall through
          case 51: break;
          case 7:
            { return symbol(sym.PARENTHESES_OPEN);
            }
          // fall through
          case 52: break;
          case 8:
            { return symbol(sym.PARENTHESES_CLOSE);
            }
          // fall through
          case 53: break;
          case 9:
            { return symbol(sym.MULTIPLICATION);
            }
          // fall through
          case 54: break;
          case 10:
            { return symbol(sym.ADDITION);
            }
          // fall through
          case 55: break;
          case 11:
            { return symbol(sym.COMMA);
            }
          // fall through
          case 56: break;
          case 12:
            { return symbol(sym.SUBTRACTION);
            }
          // fall through
          case 57: break;
          case 13:
            { return symbol(sym.DIVISION);
            }
          // fall through
          case 58: break;
          case 14:
            { return symbol(sym.INTEGER);
            }
          // fall through
          case 59: break;
          case 15:
            { return symbol(sym.SEMICOLON);
            }
          // fall through
          case 60: break;
          case 16:
            { return symbol(sym.LESS_THAN);
            }
          // fall through
          case 61: break;
          case 17:
            { return symbol(sym.EQ);
            }
          // fall through
          case 62: break;
          case 18:
            { return symbol(sym.GREATER_THAN);
            }
          // fall through
          case 63: break;
          case 19:
            { return symbol(sym.SQUARE_BRACKET_OPEN);
            }
          // fall through
          case 64: break;
          case 20:
            { return symbol(sym.SQUARE_BRACKET_CLOSE);
            }
          // fall through
          case 65: break;
          case 21:
            { return symbol(sym.XOR);
            }
          // fall through
          case 66: break;
          case 22:
            { return symbol(sym.CURLY_BRACKET_OPEN);
            }
          // fall through
          case 67: break;
          case 23:
            { return symbol(sym.CURLY_BRACKET_CLOSE);
            }
          // fall through
          case 68: break;
          case 24:
            { string.append( yytext() );
            }
          // fall through
          case 69: break;
          case 25:
            { yybegin(YYINITIAL); 
                                    return symbol(sym.STRING, 
                                    string.toString());
            }
          // fall through
          case 70: break;
          case 26:
            { string.append('\\');
            }
          // fall through
          case 71: break;
          case 27:
            { return symbol(sym.AND);
            }
          // fall through
          case 72: break;
          case 28:
            { return symbol(sym.EQEQ);
            }
          // fall through
          case 73: break;
          case 29:
            { return symbol(sym.IF);
            }
          // fall through
          case 74: break;
          case 30:
            { return symbol(sym.OR);
            }
          // fall through
          case 75: break;
          case 31:
            { string.append('\"');
            }
          // fall through
          case 76: break;
          case 32:
            { string.append('\n');
            }
          // fall through
          case 77: break;
          case 33:
            { string.append('\r');
            }
          // fall through
          case 78: break;
          case 34:
            { string.append('\t');
            }
          // fall through
          case 79: break;
          case 35:
            { return symbol(sym.CHAR);
            }
          // fall through
          case 80: break;
          case 36:
            { return symbol(sym.FLOAT);
            }
          // fall through
          case 81: break;
          case 37:
            { return symbol(sym.FOR);
            }
          // fall through
          case 82: break;
          case 38:
            { return symbol(sym.INTEGER_KEYWORD);
            }
          // fall through
          case 83: break;
          case 39:
            { return symbol(sym.BOOLEAN_KEYWORD);
            }
          // fall through
          case 84: break;
          case 40:
            { return symbol(sym.CHARACTER_KEYWORD);
            }
          // fall through
          case 85: break;
          case 41:
            { return symbol(sym.ELSE);
            }
          // fall through
          case 86: break;
          case 42:
            { return symbol(sym.SCAN);
            }
          // fall through
          case 87: break;
          case 43:
            { return symbol(sym.BOOLEAN);
            }
          // fall through
          case 88: break;
          case 44:
            { return symbol(sym.PRINT);
            }
          // fall through
          case 89: break;
          case 45:
            { return symbol(sym.WHILE);
            }
          // fall through
          case 90: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
