
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 33;
  public static final int BOOLEAN_KEYWORD = 21;
  public static final int CHARACTER_KEYWORD = 22;
  public static final int XOR = 18;
  public static final int INTEGER = 32;
  public static final int CONTINUE = 36;
  public static final int PARENTHESES_OPEN = 4;
  public static final int FOR = 27;
  public static final int GREATER_THAN = 12;
  public static final int SCAN = 29;
  public static final int NOT = 19;
  public static final int SEMICOLON = 3;
  public static final int AND = 16;
  public static final int OR = 17;
  public static final int COMMA = 2;
  public static final int SUBTRACTION = 9;
  public static final int IF = 24;
  public static final int EOF = 0;
  public static final int BOOLEAN = 31;
  public static final int RETURN = 38;
  public static final int error = 1;
  public static final int CURLY_BRACKET_CLOSE = 7;
  public static final int EQEQ = 15;
  public static final int PARENTHESES_CLOSE = 5;
  public static final int BREAK = 37;
  public static final int EQ = 14;
  public static final int ELSE = 25;
  public static final int CURLY_BRACKET_OPEN = 6;
  public static final int FLOAT_KEYWORD = 23;
  public static final int WHILE = 26;
  public static final int ADDITION = 8;
  public static final int FLOAT = 30;
  public static final int INTEGER_KEYWORD = 20;
  public static final int STRING = 34;
  public static final int DIVISION = 11;
  public static final int LESS_THAN = 13;
  public static final int MULTIPLICATION = 10;
  public static final int PRINT = 28;
  public static final int IDENTIFIER = 35;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMMA",
  "SEMICOLON",
  "PARENTHESES_OPEN",
  "PARENTHESES_CLOSE",
  "CURLY_BRACKET_OPEN",
  "CURLY_BRACKET_CLOSE",
  "ADDITION",
  "SUBTRACTION",
  "MULTIPLICATION",
  "DIVISION",
  "GREATER_THAN",
  "LESS_THAN",
  "EQ",
  "EQEQ",
  "AND",
  "OR",
  "XOR",
  "NOT",
  "INTEGER_KEYWORD",
  "BOOLEAN_KEYWORD",
  "CHARACTER_KEYWORD",
  "FLOAT_KEYWORD",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "PRINT",
  "SCAN",
  "FLOAT",
  "BOOLEAN",
  "INTEGER",
  "CHAR",
  "STRING",
  "IDENTIFIER",
  "CONTINUE",
  "BREAK",
  "RETURN"
  };
}

